### ISSUE TITLE
problem while trying to run

### ISSUE THREAD

**Issue by repka3** [Ra-Coding/idle-game-generator-visualization-tool#10]
simple as this:

# ./gradlew run

> Configure project :
Project : => 'Main' Java module

> Task :run FAILED
WARNING: Unknown module: Main specified to --patch-module
Error: Could not find or load main class idle.game.generator.visualization.tool.App
Caused by: java.lang.ClassNotFoundException: idle.game.generator.visualization.tool.App

FAILURE: Build failed with an exception.
Tried with Java 11 and Java 16 and Java 1.8

**Comment by Fireball19** [comment]
Hey, thanks for the bug report!

I updated the JavaFX Gradle plugin to version 0.1.0 (release 1.2.1).

`./gradlew run` should work again (with Java 17).

**Comment by repka3** [comment]
Thank you ! Can confirm now it works (with Java 16.0.2 nonetheless) !

**Comment by Fireball19** [comment]
Great! I will close the issue.
